site_name: demo-site
site_description: 'A mkdocs based static site'
site_author: 'Shivdeep SIngh'
docs_dir: docs/
repo_name: 'mhausenblas/mkdocs-template'
repo_url: 'https://github.com/mhausenblas/mkdocs-template'
nav:
    - Home: docs/index.md
theme:
  name: 'material'
  palette:
    primary: teal
